export const USERID_CHANGED = 'userid_changed';
export const PASSWORD_CHANGED = 'password_changed';
export const REMEMBER_ME_CHANGED = 'REMEMBER_ME_CHANGED';
export const LOAD_SAVED_USER_PASS = 'LOAD_SAVED_USER_PASS';
export const LOAD_SAVED_SESSION = 'LOAD_SAVED_SESSION';
export const LOGIN_USER_SUCCESS = 'login_user_success';
export const LOGIN_USER_FAIL = 'login_user_fail';
export const LOGIN_USER = 'login_user';
export const LOGOUT_USER = 'logout_user';
export const LOGOUT = 'LOGOUT';

export const PDLIST_FETCH = 'pdlist_fetch';
export const PDLIST_FETCH_SUCCESS = 'pdlist_fetch_success';
export const PDLIST_FETCH_FAIL = 'pdlist_fetch_fail';
export const PDLIST_NO_TRIP = 'PDLIST_NO_TRIP';

export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS';
export const UPDATE_ORDER_STATUS_FAIL = 'UPDATE_ORDER_STATUS_FAIL';

export const PD_UPDATE_WEIGHT_SIZE = 'PD_UPDATE_WEIGHT_SIZE';
export const PD_UPDATE_WEIGHT_SIZE_SUCCESS = 'PD_UPDATE_WEIGHT_SIZE_SUCCESS';
export const PD_UPDATE_WEIGHT_SIZE_FAIL = 'PD_UPDATE_WEIGHT_SIZE_FAIL';

export const PD_UPDATE_GROUP = 'PD_UPDATE_GROUP';
export const PD_UPDATE_GROUP_SUCCESS = 'PD_UPDATE_GROUP_SUCCESS';
export const PD_UPDATE_GROUP_FAIL = 'PD_UPDATE_GROUP_FAIL';

export const OTHER_GET_CONFIGURATION = 'OTHER_GET_CONFIGURATION';
export const OTHER_GET_CONFIGURATION_SUCCESS = 'OTHER_GET_CONFIGURATION_SUCCESS';
export const OTHER_GET_CONFIGURATION_FAIL = 'OTHER_GET_CONFIGURATION_FAIL';
export const OTHER_CALCULATE_FEE_SUCCESS = 'OTHER_CALCULATE_FEE_SUCCESS';
export const OTHER_CALCULATE_FEE = 'OTHER_CALCULATE_FEE';
export const OTHER_GET_USER_PERFORMANCE = 'OTHER_GET_USER_PERFORMANCE';
export const OTHER_GET_USER_PERFORMANCE_SUCCESS = 'OTHER_GET_USER_PERFORMANCE_SUCCESS';

