export const USERID_CHANGED = 'userid_changed';
export const PASSWORD_CHANGED = 'password_changed';
export const REMEMBER_ME_CHANGED = 'REMEMBER_ME_CHANGED';
export const LOAD_SAVED_USER_PASS = 'LOAD_SAVED_USER_PASS';
export const LOAD_SAVED_SESSION = 'LOAD_SAVED_SESSION';
export const LOGIN_USER_SUCCESS = 'login_user_success';
export const LOGIN_USER_FAIL = 'login_user_fail';
export const LOGIN_USER = 'login_user';
export const LOGOUT_USER = 'logout_user';
export const LOGOUT = 'LOGOUT';
export const GO_SUPPORT = 'GO_SUPPORT';

export const PDLIST_FETCH = 'pdlist_fetch';
export const PDLIST_FETCH_SUCCESS = 'pdlist_fetch_success';
export const PDLIST_FETCH_FAIL = 'pdlist_fetch_fail';
export const PDLIST_NO_TRIP = 'PDLIST_NO_TRIP';

export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS';
export const UPDATE_ORDER_STATUS_FAIL = 'UPDATE_ORDER_STATUS_FAIL';

export const PD_UPDATE_WEIGHT_SIZE = 'PD_UPDATE_WEIGHT_SIZE';
export const PD_UPDATE_WEIGHT_SIZE_SUCCESS = 'PD_UPDATE_WEIGHT_SIZE_SUCCESS';
export const PD_UPDATE_WEIGHT_SIZE_FAIL = 'PD_UPDATE_WEIGHT_SIZE_FAIL';

export const PD_UPDATE_GROUP = 'PD_UPDATE_GROUP';
export const PD_UPDATE_GROUP_SUCCESS = 'PD_UPDATE_GROUP_SUCCESS';
export const PD_UPDATE_GROUP_FAIL = 'PD_UPDATE_GROUP_FAIL';

export const PD_ADD_ORDER = 'PD_ADD_ORDER';
export const PD_ADD_ORDER_FAIL = 'PD_ADD_ORDER_FAIL';
export const PD_ADD_ORDER_START = 'PD_ADD_ORDER_START';

export const PD_UPDATE_ORDER_INFO = 'PD_UPDATE_ORDER_INFO';
export const PD_UPDATE_ORDER_INFOS = 'PD_UPDATE_ORDER_INFOS';
export const PD_TOGGLE_GROUP_ACTIVE = 'PD_TOGGLE_GROUP_ACTIVE';

export const PD_TOGGLE_ORDER_GROUP = 'PD_TOGGLE_ORDER_GROUP';
export const PD_CREATE_GROUP = 'PD_CREATE_GROUP';
export const PD_RESET_GROUP = 'PD_RESET_GROUP';
export const PD_UPDATE_ORDERS = 'PD_UPDATE_ORDERS';

export const OTHER_GET_CONFIGURATION = 'OTHER_GET_CONFIGURATION';
export const OTHER_GET_CONFIGURATION_SUCCESS = 'OTHER_GET_CONFIGURATION_SUCCESS';
export const OTHER_GET_CONFIGURATION_FAIL = 'OTHER_GET_CONFIGURATION_FAIL';
export const OTHER_CALCULATE_FEE_SUCCESS = 'OTHER_CALCULATE_FEE_SUCCESS';
export const OTHER_CALCULATE_FEE = 'OTHER_CALCULATE_FEE';
export const OTHER_GET_USER_PERFORMANCE = 'OTHER_GET_USER_PERFORMANCE';
export const OTHER_GET_USER_PERFORMANCE_SUCCESS = 'OTHER_GET_USER_PERFORMANCE_SUCCESS';
export const OTHER_GET_USER_PERFORMANCE_FAIL = 'OTHER_GET_USER_PERFORMANCE_FAIL';

export const PICKGROUP_UPDATE_ORDER_INFO = 'PICKGROUP_UPDATE_ORDER_INFO';
export const PICKGROUP_UPDATE_ALL_ORDER_INFO = 'PICKGROUP_UPDATE_ALL_ORDER_INFO';
export const PICKGROUP_SET_ALL_STATUS = 'PICKGROUP_SET_ALL_STATUS';
export const PICKGROUP_RESET = 'PICKGROUP_RESET';
export const PICKGROUP_CHANGE_DONE = 'PICKGROUP_CHANGE_DONE';
export const PICKGROUP_CHANGE_KEYWORD = 'PICKGROUP_CHANGE_KEYWORD';

export const RETURNGROUP_UPDATE_ORDER_INFO = 'RETURNGROUP_UPDATE_ORDER_INFO';
export const RETURNGROUP_UPDATE_ALL_ORDER_INFO = 'RETURNGROUP_UPDATE_ALL_ORDER_INFO';
export const RETURNGROUP_SET_ALL_STATUS = 'RETURNGROUP_SET_ALL_STATUS';
export const RETURNGROUP_RESET = 'RETURNGROUP_RESET';
export const RETURNGROUP_CHANGE_DONE = 'RETURNGROUP_CHANGE_DONE';
export const RETURNGROUP_CHANGE_KEYWORD = 'RETURNGROUP_CHANGE_KEYWORD';


export const ORDER_CHANGE_ORDER_CODE = 'ORDER_CHANGE_ORDER_CODE';
export const ORDER_GET_ORDER_START = 'ORDER_GET_ORDER_START';
export const ORDER_GET_ORDER = 'ORDER_GET_ORDER';
export const ORDER_GET_ORDER_FAIL = 'ORDER_GET_ORDER_FAIL';
export const ORDER_ADD_ORDER_START = 'ORDER_ADD_ORDER_START';
export const ORDER_ADD_ORDER = 'ORDER_ADD_ORDER';
export const ORDER_ADD_ORDER_FAIL = 'ORDER_ADD_ORDER_FAIL';
